require 'em-aws'

module EventMachine
  module AWS
    module Query
      
      # Exceptions generated by responses from the Amazon Query Protocol.
      class QueryError < AWS::Error
        attr_reader :status, :code, :description
        def initialize(status, code, description=nil)
          @status, @code, @description = status, code, description
        end
        
        def message
          "#{code}: #{description} (#{status})"
        end
      end
      
      
    end
  end
end